version: '2'
services:
  web_2:
    image: "httpd"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - api

  data: #docker run --name some-mongo -d mongo
    image: "mongo"
    expose:
     - "27017"

  api:
    build: ./api
    expose:
     - "5555"
    depends_on:
     - data
